/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class MemoryEngine {
  static create(configJson?: string | undefined | null): Promise<MemoryEngine>
  add(messages: Array<JsChatMessage>, userId?: string | undefined | null, agentId?: string | undefined | null, runId?: string | undefined | null, metadata?: string | undefined | null, infer?: boolean | undefined | null): Promise<JsAddResult>
  search(query: string, userId?: string | undefined | null, agentId?: string | undefined | null, runId?: string | undefined | null, limit?: number | undefined | null, filters?: string | undefined | null, rerank?: boolean | undefined | null, threshold?: number | undefined | null): Promise<JsSearchResult>
  get(memoryId: string): Promise<JsMemoryItem>
  getAll(userId?: string | undefined | null, agentId?: string | undefined | null, runId?: string | undefined | null, filters?: string | undefined | null, limit?: number | undefined | null): Promise<Array<JsMemoryItem>>
  update(memoryId: string, newText: string): Promise<void>
  delete(memoryId: string): Promise<void>
  deleteAll(userId?: string | undefined | null, agentId?: string | undefined | null, runId?: string | undefined | null): Promise<void>
  history(memoryId: string): Promise<Array<JsMemoryEvent>>
  reset(): Promise<void>
}
export type JsMemoryEngine = MemoryEngine

export interface JsAddResult {
  results: Array<JsMemoryActionResult>
  relations: Array<JsGraphRelation>
}

export interface JsChatMessage {
  role: string
  content: string
}

export declare const enum JsMemoryAction {
  Add = 'Add',
  Update = 'Update',
  Delete = 'Delete',
  None = 'None'
}

export interface JsMemoryActionResult {
  id: string
  action: JsMemoryAction
  oldValue?: string
  newValue?: string
}

export interface JsMemoryEvent {
  id: string
  memoryId: string
  oldValue?: string
  newValue?: string
  action: JsMemoryAction
  createdAt: string
}

export interface JsGraphRelation {
  source: string
  relationship: string
  destination: string
  score?: number
}

export interface JsMemoryItem {
  id: string
  text: string
  userId?: string
  agentId?: string
  runId?: string
  metadata: string
  createdAt: string
  updatedAt: string
  score?: number
  lastAccessedAt?: string
  accessCount: number
}

export interface JsSearchResult {
  memories: Array<JsMemoryItem>
  relations: Array<JsGraphRelation>
}
